[package]
name = "poki-launcher"
version = "0.1.0"
build = "build.rs"
links = "poki-launcher"
edition = "2018"

[dependencies]
libc = "0.2"
gtk = "0.7"
lib-poki-launcher = { path = "../launcher" }

[build-dependencies]
rust_qt_binding_generator = "0.3"
